import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import "bootstrap/dist/css/bootstrap.min.css";
// import styles from '../styles/Home.module.css'
import {useState} from 'react';
import axios from 'axios'

// const inter = Inter({ subsets: ['latin'] })
var pageCounter = 1;
export default function Home() {
  // const [keyword, setKeyword] = useState(null);
  const [response, setResponse] = useState(null);
  const getAnimal = async () => {
		try {
			const res = await axios.get(`https://raw.githubusercontent.com/LearnWebCode/json-example/master/animals-${pageCounter}.json`);
			const {data} = res;
			setResponse(data); // Store the response

      pageCounter++;
      if(pageCounter > 3) {
        pageCounter = 1;
      }
      
 		} catch (error) {
			console.log(error);
		}
	};

  return (
    <>
      <Head>
        <title>Animal Name JSON</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Muhammad Faqih" />
        <meta name="NIM" content="2020230032" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <div className="d-flex flex-column min-vh-100 justify-content-center align-items-center">
          <div>
            <h1>Animal Data</h1>
          </div>

          <div>
            <form
              onSubmit={e => {
                getAnimal();
                e.preventDefault();
                e.stopPropagation();
              }}
              >
           
              <button type="submit" className="btn btn-primary">Submit</button>
           </form>
          </div>

          {response && (
            <div className='mt-5'>
              <h1>Page: {pageCounter}</h1>
              <table className="table">
                <thead>
                  <tr>
                    <th>Nama</th>
                    <th>Foods</th>
                    <th>Dislike Foods</th>
                  </tr>
                </thead>
                <tbody>
               
                {
                  response.map((element, index) => {
                    return (
                        <tr key={index}>
                        <td>{element.name} is a {element.species}</td>
                        <td>{element.foods.likes[0]} {element.foods.likes[1]}</td>
                        <td>{element.foods.dislikes[0]} {element.foods.dislikes[1]}</td>
                      </tr>
                      
                    )
                  })
                }
                </tbody>
              </table>
            </div>
          )}    
          
        </div>

        <div className="mt-10 text-center">
          <p className="text-primary text-xs font-light">
            Made by siberfaqih -{" "}
            <a
              target="_blank"
	      rel="noreferrer"
              className="hover:text-active"
              href="https://github.com/siberfaqih/"
            >
              See my github
            </a>
          </p>
        </div>
      </main>

       

    </>
  )
}
